n1 = int (input('digite o primeiro numero : '))
n2 = int (input('digite o segundo numero : '))
print ('Soma :' , n1 + n2 )
print ('Subtração :' , n1 - n2 )
print ('Multiplicação :' , n1 * n2 )
print ('Divisão :' , n1 / n2 )
